name: Daily Commit Bot

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 8 AM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update timestamp
        run: |
          echo "Last update: $(date -u)" > timestamp.txt

      - name: Commit and push
        run: |
          git config user.name "auto-commit-bot"
          git config user.email "bot@example.com"
          git add timestamp.txt
          git commit -m "chore: daily update"
          git push
